### ISSUE TITLE
Сайт sledcom.ru

### ISSUE THREAD

**Issue by audetv** [terratensor/feed-parser#19]
Стоит ли добавить в парсер новости с сайта: Следственный комитет Российской Федерации?
https://sledcom.ru/

Есть 2 ленты, main=1, я так понимаю главные события 
https://sledcom.ru/news/rss_verify/?main=1

main=0 региональные события
https://sledcom.ru/news/rss_verify/?main=0

Новости на английском языке перестали публиковать в 2022 году.

Поиск kremlin.ru | mil.ru | mid.ru | sledcom.ru …

**Comment by iprst** [comment]
Возможно это следующая фаза? СК, ГП, ФСБ, МЧС, МВД

**Comment by audetv** [comment]
Да, я думаю это следующая фаза, пока завершу с текущими 3мя сайтами, еще мид индексер нужно сделать и фронтенд сделать. Сейчас фронтенд — это прост прототип. И потихоньку посмотрю, изучу другие сайт, вышеуказанные, что там за rss ленты, как устроены. Пусть будет в фоне задача.

**Comment by iprst** [comment]
Ещё по сайту именно СК — довольно тормозная конструкция. Актуальные новости в телеге у них идут значительно резвее. Из СК было бы полезно вынуть информацию про преступления хунты, там есть специальный раздел. 
https://sledcom.ru/cases/item/1168/

**Comment by audetv** [comment]
> Ещё по сайту именно СК — довольно тормозная конструкция. Актуальные новости в телеге у них идут значительно резвее.

Понял, хорошо, думаю можно и из телеги новости забирать., на до посмотреть.

> Из СК было бы полезно вынуть информацию про преступления хунты, там есть специальный раздел.
> https://sledcom.ru/cases/item/1168/

Да, хорошо. Посмотрю. Надо подумать.  Фигуранты преступлений ФИО, и сами события.
